CREATE DATABASE dbAgencia_Viagens_;
GO

USE dbAgencia_Viagens_;
GO

CREATE TABLE [PACOTE VIAGEM] (
    Codigo INT IDENTITY(1,1) PRIMARY KEY,
    Origem VARCHAR(100),
    Destino VARCHAR(100),
    DataInicio DATE,
    DataFinal DATE,
    ValorTotal DECIMAL(10,2)
);
GO

-- SELECT * FROM [PACOTE VIAGEM]

-- teste
INSERT INTO [PACOTE VIAGEM]
(ORIGEM, DESTINO, DATAINICIO, DATAFINAL, VALORTOTAL)
VALUES ('ORIGEM', 'DESTINO', NULL, NULL, NULL);
GO

SELECT * FROM [PACOTE VIAGEM];